---
- name: eucalyptus configuration script for ceph
  copy:
    src: ceph-euca-setup.sh
    dest: /root/ceph-euca-setup.sh
    owner: root
    group: root
    mode: 0755

- name: eucalyptus configuration for ceph
  command:
    chdir: /root/
    cmd: /root/ceph-euca-setup.sh
    creates: /root/eucalyptus/ceph/ceph.conf
  environment:
    EUCA_CEPH_ARTIFACTS_DIR: /root/eucalyptus/ceph
    EUCA_POOL_PLACEMENT_GROUPS: 60

- name: eucalyptus gather ceph configuration
  slurp:
    path: /root/eucalyptus/ceph/ceph.conf
  register: slurp_result

- name: set eucalyptus ceph configuration fact
  set_fact:
    cacheable: yes
    eucalyptus_ceph_conf: "{{ slurp_result.content | b64decode }}"

- name: eucalyptus gather ceph client keyring
  slurp:
    path: /root/eucalyptus/ceph/ceph.client.eucalyptus.keyring
  register: slurp_result

- name: set eucalyptus ceph client keyring fact
  set_fact:
    cacheable: yes
    eucalyptus_ceph_keyring: "{{ slurp_result.content | b64decode }}"

- name: eucalyptus gather ceph radosgw s3 credentials
  slurp:
    path: /root/eucalyptus/ceph/rgw_credentials.json
  register: slurp_result

- name: set eucalyptus ceph radosgw s3 credentials fact
  set_fact:
    cacheable: yes
    eucalyptus_ceph_rgw_creds: "{{ slurp_result.content | b64decode | from_json }}"

