---
- name: configure permissive mode selinux
  selinux:
    policy: targeted
    state: permissive
  tags:
    - image

- name: disable firewalld
  systemd:
    enabled: no
    state: stopped
    name: firewalld
  tags:
    - image
  register: systemd_result
  failed_when: "systemd_result is failed and 'Could not find the requested service' not in systemd_result.msg"

- name: install eucalyptus package
  yum:
    name: eucalyptus
    state: present
  tags:
    - image
    - packages

- name: eucalyptus configuration
  template:
    src: eucalyptus.conf.j2
    dest: /etc/eucalyptus/eucalyptus.conf
    owner: root
    group: root
    mode: 0644
