---
- import_tasks: yum_repos.yml
  tags:
    - image
    - packages

- import_tasks: yum_repos_vpcmido.yml
  tags:
    - image
    - packages
  when: net_mode == "VPCMIDO"

- import_tasks: base_packages.yml

- import_tasks: base_config.yml

- import_tasks: key_facts.yml
  delegate_to: "{{ groups['cloud'][0] }}"
  run_once: yes
  when: key_facts
