---
name: ciab-console
description: 'Eucalyptus cloud-in-a-box, including eucaconsole'
template_aliases: ETP_TEMPLATE_ALIASES
default_attributes:
    eucalyptus:
        <<: *alias_eucalyptus
        cloud-opts: 'ETP_EUCALYPTUS_CLOUD_OPTS'
        cloud-properties:
            <<: *alias_eucalyptus_cloud_properties
        topology:
            clc: [ETP_HOST0_IP]  # ETP_HOST0_NAME
            objectstorage:
                providerclient: walrus
                walrusbackend: [ETP_HOST0_IP]  # ETP_HOST0_NAME
            user-facing: [ETP_HOST0_IP]  # ETP_HOST0_NAME
            console: [ETP_HOST0_IP]  # ETP_HOST0_NAME
            clusters:
                one:
                    storage-backend: overlay
                    cc: [ETP_HOST0_IP]  # ETP_HOST0_NAME
                    sc: [ETP_HOST0_IP]  # ETP_HOST0_NAME
                    nodes: [ETP_HOST0_IP]  # ETP_HOST0_NAME
        cc:
            <<: *alias_eucalyptus_cc
        nc:
            <<: *alias_eucalyptus_nc
        network:
            mode: EDGE
            InstanceDnsServers: [ETP_HOST0_IP]  # ETP_HOST0_NAME
            PublicIps: [ETP_PUBLIC_IP_RANGE]
            clusters:
                - Name: one
                  PrivateIps: [ETP_PRIVATE_IP_RANGE]
                  Subnet:
                      Subnet: ETP_SUBNET
                      Name: ETP_SUBNET
                      Netmask: ETP_NETMASK
                      Gateway: ETP_GATEWAY
            bridge-interface: br0
            public-interface: br0
            private-interface: br0
            bridged-nic: ETP_NODE_NIC
            dns-server: ETP_DNS_SERVER
override_attributes: {}
cookbook_versions: {}
