---
name: vpc
description: 'Eucalyptus cloud with poc vpc networking and das storage'
template_aliases: ETP_TEMPLATE_ALIASES
default_attributes:
    eucalyptus:
        <<: *alias_eucalyptus
        cloud-opts: 'ETP_EUCALYPTUS_CLOUD_OPTS'
        cloud-properties:
            <<: *alias_eucalyptus_cloud_properties
        topology:
            clc: [ETP_HOST0_IP]  # ETP_HOST0_NAME
            objectstorage:
                providerclient: walrus
                walrusbackend: [ETP_HOST0_IP]  # ETP_HOST0_NAME
            user-facing: [ETP_HOST0_IP]  # ETP_HOST0_NAME
            clusters:
                one:
                    storage-backend: das
                    das-device: ETP_DAS_DEVICE
                    cc: [ETP_HOST0_IP]  # ETP_HOST0_NAME
                    sc: [ETP_HOST0_IP]  # ETP_HOST0_NAME
                    nodes: [ETP_HOST1_IP]  # ETP_HOST1_NAME
        cc:
            <<: *alias_eucalyptus_cc
        nc:
            <<: *alias_eucalyptus_nc
        network:
            mode: VPCMIDO
            InstanceDnsServers: [ETP_HOST0_IP]  # ETP_HOST0_NAME
            PublicIps: [ETP_HOST0_VPC_PUBLIC_IP_RANGE]
            bridge-interface: br0
            public-interface: ETP_NODE_NIC
            private-interface: ETP_NODE_NIC
            bridged-nic: ETP_NODE_NIC
            dns-server: ETP_DNS_SERVER
        midonet:
            <<: *alias_eucalyptus_midonet
            Gateways:
                - <<: *alias_eucalyptus_midonet_gateway0
                  Ip: ETP_HOST0_IP
                  ExternalIp: ETP_HOST0_VPC_GATEWAY_IP
            midolman-host-mapping:
                ETP_HOST0_NAME: ETP_HOST0_IP
                ETP_HOST1_NAME: ETP_HOST1_IP
    cassandra:
        topology: [ETP_HOST0_IP]  # ETP_HOST0_NAME
    thrift:
        version: 0.9.1
    zookeeper:
        topology: [ETP_HOST0_IP]  # ETP_HOST0_NAME
override_attributes: {}
cookbook_versions: {}

