---
# Cloud settings
cloud_region_region_name: eucalyptus
cloud_zone_1_name: one
cloud_listener_cidr: 0.0.0.0/0

# EDGE network settings
edge_subnet: "{{ ansible_default_ipv4.network }}"
edge_netmask: "{{ ansible_default_ipv4.netmask }}"
edge_gateway: "{{ ansible_default_ipv4.gateway }}"
edge_private_ip_range: 192.168.254.150-192.168.254.199
edge_public_ip_range: 192.168.254.200-192.168.254.249

# Midonet settings
midonet_cassandra_name: Eucalyptus Midonet Cluster
midonet_cassandra_heap: Null
midonet_cassandra_heapnew: Null
midonet_zookeeper_heap: Null
midonet_cluster_heap: Null
midonet_midolman_heap: Null

# VPCMIDO network settings
vpcmido_public_ip_range: 192.168.254.150-192.168.254.250
vpcmido_public_ip_cidr: 192.168.254.128/25
vpcmido_gw_ext_cidr: 10.234.234.224/27
vpcmido_gw_ext_device: euca-mgw-veth1
vpcmido_gw_ext_ip: 10.234.234.235
vpcmido_gw_ext_router_ip: 10.234.234.234
vpcmido_gw_srv_veth_create: "{{ vpcmido_gw_ext_device == 'euca-mgw-veth1' }}"
vpcmido_gw_srv_veth0: euca-mgw-veth0
vpcmido_gw_srv_veth1: euca-mgw-veth1
vpcmido_gw_srv_veth_prefix: 27

# Network settings
net_mode: EDGE
net_mode_lower: "{{ net_mode | lower }}"
net_mode_:
  edge:
    private_ip_range: "{{ edge_private_ip_range }}"
    public_ip_range: "{{ edge_public_ip_range }}"
  vpcmido:
    private_ip_range: Null
    public_ip_range: "{{ vpcmido_public_ip_range }}"
net_private_ip_range: "{{ net_mode_[net_mode_lower]['private_ip_range'] }}"
net_public_ip_range: "{{ net_mode_[net_mode_lower]['public_ip_range'] }}"
