# Cloud settings
cloud_region_region_name: eucalyptus
cloud_zone_1_name: one

# Edge network settings
edge_subnet: 192.168.240.0
edge_netmask: 255.255.255.0
edge_gateway: 192.168.240.1

# Network settings
net_mode: EDGE
net_private_ip_range: 192.168.240.100-192.168.240.120
net_public_ip_range: 192.168.240.200-192.168.240.220
