---
- name: configure permissive mode selinux
  selinux:
    policy: targeted
    state: permissive
  tags:
    - image

- name: disable firewalld
  service:
    name: firewalld.service
    enabled: no
    state: stopped
  tags:
    - image

