---
# Eucalyptus playbook
- hosts: all
  gather_facts: no
  tasks:
  - import_tasks: host_groups.yml

- hosts: ceph:ceph_object_gateway:ceph_deploy
  roles:
  - ceph-host

- hosts: ceph_deploy
  roles:
  - ceph

- hosts: cloud
  roles:
  - cloud
  - console

- hosts: node
  roles:
  - node

- hosts: cloud
  roles:
  - zone
  - cloud-post

