---
kernel:
  image: linuxkit/kernel:4.14.81
  cmdline: "console=ttyS0 root=/dev/vda1"
init:
  - linuxkit/init:c563953a2277eb73a89d89f70e4b6dcdcfebc2d1
  - linuxkit/runc:83d0edb4552b1a5df1f0976f05f442829eac38fe
  - linuxkit/containerd:326b096cd5fbab0f864e52721d036cade67599d6
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:v0.6
services:
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: sshd
    image: linuxkit/sshd:c4bc89cf0d66733c923ab9cb46198b599eb99320
    binds:
     - /run/config/ssh/authorized_keys:/root/.ssh/authorized_keys
     - /etc/ssh/sshd_config:/etc/ssh/sshd_config
files:
  - path: /etc/ssh/sshd_config
    mode: "0664"
    contents: |
      AuthorizedKeysFile .ssh/authorized_keys
      ChallengeResponseAuthentication no
      ForceCommand nsenter --target 1 --mount
      PasswordAuthentication no
trust:
  org:
    - linuxkit
    - library
